# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a551203a-172b-449d-bb5f-1526e0706868";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:9" ];
    };

  boot.initrd.luks.devices."luks-9ab4f688-fc14-4a7b-9949-af453956f2a2".device = "/dev/disk/by-uuid/9ab4f688-fc14-4a7b-9949-af453956f2a2";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/2CE7-D80A";
      fsType = "vfat";
    };

  fileSystems."/home/roxo/mnt/manjaro" =
    { device = "/dev/disk/by-uuid/676061cf-2319-45d5-bd3b-ebc36622262f";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d935b127-6ab6-4b48-91da-1a45cd48eb50"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
