# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1c539cd8-9c32-45a0-9a58-4c94d295ed56";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:9" ];
    };

  boot.initrd.luks.devices."luks-b95f4e25-cc86-419e-96e3-70d1f4e406fc".device = "/dev/disk/by-uuid/b95f4e25-cc86-419e-96e3-70d1f4e406fc";
  boot.initrd.luks.devices."luks-c0d2f502-d907-4a7e-99d8-ccdc70f1e4a1".device = "/dev/disk/by-uuid/c0d2f502-d907-4a7e-99d8-ccdc70f1e4a1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/48D3-28F9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/roxo/mnt/manjaro" =
    { device = "/dev/disk/by-uuid/676061cf-2319-45d5-bd3b-ebc36622262f";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6998f9b6-7cf4-4367-9bb0-303cad324a6e"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
